DEFAULT_SERVER_URL        = Rails.application.config_for(:server)["server_url"]
DEFAULT_DONE_DELAY        = Rails.application.config_for(:server)["done_delay"]
DEFAULT_LOCATE_ME_SECONDS = Rails.application.config_for(:server)["locate_me_seconds"]
DEFAULT_LOGIN_INTERVAL    = Rails.application.config_for(:server)["login_interval"]
DEFAULT_PING_INTERVAL     = Rails.application.config_for(:server)["ping_interval"]
