development:
  server_url:        ws://192.168.0.10:8080
  done_delay:        500
  locate_me_seconds: 5
  login_interval:    5000

production:
  server_url: ws://glosho.herokuapp.com
  done_delay:        500
  locate_me_seconds: 5
  login_interval:    5000
